/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	tutorialSidebar: [
		{
			type: "html",
			value: '<div class="sidebar-section-header">Getting Started</div>',
			className: "sidebar-section getting-started-section",
		},
		{
			type: "doc",
			id: "workspace/index",
			label: "Workspace Overview",
		},
		{ type: "autogenerated", dirName: "workspace/getting-started" },
		{
			type: "html",
			value: '<div class="sidebar-section-header">Developers</div>',
			className: "sidebar-section developers-section",
		},
		{ type: "autogenerated", dirName: "workspace/developers" },
		{
			type: "html",
			value: '<div class="sidebar-section-header">Analyst</div>',
			className: "sidebar-section analyst-section",
		},
		{ type: "autogenerated", dirName: "workspace/analysts" },
		{
			type: "html",
			value: '<span class="sidebar-divider" />',
		},
		{
			type: "category",
			label: "OpenBB Platform",
			items: [{ type: "autogenerated", dirName: "platform" }],
		},
		{
			type: "category",
			label: "OpenBB Platform CLI",
			items: [{ type: "autogenerated", dirName: "cli" }],
		},
		// Can do stuff like this too
		// {
		//   type: "html",
		//   defaultStyle: true,
		//   className: "powered-by-banner",
		//   value: `
		//     <span>Powered by</span>
		//     <img src="/img/docusaurus.png" alt="Docusaurus Logo" />
		//   `,
		// },
	],

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};
