/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	tutorialSidebar: [
		{
			type: "category",
			label: "Getting Started",
			className: "sidebar-section getting-started-section",
			items: [
				{ type: "doc", id: "workspace/index", label: "Workspace Overview" },
				{ type: "autogenerated", dirName: "workspace/getting-started" },
			],
		},
		{
			type: "category",
			label: "Agents",
			className: "sidebar-section agents-section",
			items: [
				{
					type: "doc",
					id: "agents/workspace-mcp-overview",
					label: "Workspace MCP Overview",
				},
				{
					type: "doc",
					id: "agents/workspace-mcp-quickstart",
					label: "Workspace MCP Quickstart",
				},
				{
					type: "doc",
					id: "agents/workspace-mcp-tools",
					label: "Workspace MCP Tools",
				},
				{
					type: "doc",
					id: "agents/app-builder-resources",
					label: "App Builder Resources",
				},
			],
		},
		{
			type: "category",
			label: "Analyst",
			className: "sidebar-section analyst-section",
			items: [{ type: "autogenerated", dirName: "workspace/analysts" }],
		},
		{
			type: "category",
			label: "Developers",
			className: "sidebar-section developers-section",
			items: [{ type: "autogenerated", dirName: "workspace/developers" }],
		},
		{
			type: "category",
			label: "Desktop",
			className: "sidebar-section odp-desktop-section",
			link: { type: "doc", id: "odp/desktop/index" },
			items: [{ type: "autogenerated", dirName: "odp/desktop" }],
		},
		{
			type: "category",
			label: "Python",
			className: "sidebar-section odp-python-section",
			link: { type: "doc", id: "odp/python/index" },
			items: [{ type: "autogenerated", dirName: "odp/python" }],
		},
		{
			type: "category",
			label: "CLI",
			className: "sidebar-section odp-cli-section",
			link: { type: "doc", id: "odp/cli/index" },
			items: [{ type: "autogenerated", dirName: "odp/cli" }],
		},
		{
			type: "category",
			label: "Snowflake",
			className: "sidebar-section snowflake-section",
			items: [{ type: "autogenerated", dirName: "snowflake" }],
		},
		// Can do stuff like this too
		// {
		//   type: "html",
		//   defaultStyle: true,
		//   className: "powered-by-banner",
		//   value: `
		//     <span>Powered by</span>
		//     <img src="/img/docusaurus.png" alt="Docusaurus Logo" />
		//   `,
		// },
	],

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};
