import { useLocation } from "@docusaurus/router";
import DocSidebarItemCategory from "@theme/DocSidebarItem/Category";
import DocSidebarItemHtml from "@theme/DocSidebarItem/Html";
import DocSidebarItemLink from "@theme/DocSidebarItem/Link";
import { useIFrameContext } from "../Root.tsx";

function shouldHideItem(item, productPath) {
	if (item.items) {
		return item.items.every((childItem) =>
			shouldHideItem(childItem, productPath),
		);
	}

	if (item.type === "link") {
		const itemPath = item.href.replace(/\/$/, "");
		return !itemPath.startsWith(productPath);
	}

	if (item.type === "category") {
		return item.items.every((childItem) =>
			shouldHideItem(childItem, productPath),
		);
	}

	return false;
}

export default function DocSidebarItem({ item, ...props }) {
	const { isIFrame } = useIFrameContext();
	const { pathname } = useLocation();
	const isPro = pathname.startsWith("/workspace");
	const isExcel = pathname.startsWith("/excel");
	const isGettingStarted = pathname.startsWith("/getting-started");
	const isPlatform = pathname.startsWith("/platform");
	const isCLI = pathname.startsWith("/cli");
	const isODP = pathname.startsWith("/odp");
	const isRelevantSection = isPro || isExcel || isGettingStarted;

	// Only show workspace items when in workspace, excel items when in excel, getting-started items always in relevant sections
	if (item.type === "autogenerated") {
		// Hide ALL workspace directories and subdirectories when not in workspace
		if (item.dirName?.startsWith("workspace") && !isPro) {
			return null;
		}
		if (item.dirName === "excel" && !isExcel) {
			return null;
		}
		if (item.dirName === "getting-started" && !isRelevantSection) {
			return null;
		}
	}

	// Hide workspace index page from autogenerated workspace items since it's manually added to getting started
	if (item.type === "link" && item.href === "/workspace" && item.docId?.includes("workspace/")) {
		return null;
	}
	
	// Hide workspace overview when in platform
	if (isPlatform && item.type === "doc" && item.id === "workspace/index") {
		return null;
	}

	// Show section headers only when in workspace, excel, or getting-started sections
	// Hide them when in platform, CLI or other sections
	if (item.className?.includes("getting-started-section") && (!isRelevantSection || isPlatform || isCLI || isODP)) {
		return null;
	}
	if (item.className?.includes("developers-section") && (!isRelevantSection || isPlatform || isCLI || isODP)) {
		return null;
	}
	if (item.className?.includes("analyst-section") && (!isRelevantSection || isPlatform || isCLI || isODP)) {
		return null;
	}

	if (isIFrame) {
		const firstTwoPathSegments = pathname.split("/").slice(0, 3).join("/");

		if (shouldHideItem(item, firstTwoPathSegments)) {
			return null;
		}
	}

	// Hide workspace categories when in platform or CLI sections
	if ((isPlatform || isCLI || isODP) && item.type === "category") {
		// First check if the first item in the category is workspace-related (quick check)
		const firstItem = item.items?.[0];
		if (firstItem) {
			const isWorkspaceCategory = 
				firstItem.href?.startsWith("/workspace") ||
				firstItem.id?.startsWith("workspace/") ||
				firstItem.docId?.startsWith("workspace/") ||
				firstItem.dirName?.startsWith("workspace");
			
			if (isWorkspaceCategory) {
				return null;
			}
		}
		
		// Also do a thorough check
		const hasOnlyWorkspaceItems = checkIfOnlyWorkspaceItems(item);
		if (hasOnlyWorkspaceItems) {
			return null;
		}
	}
	
	// Only filter categories when in workspace/excel/getting-started sections
	// Don't filter when in platform or other sections
	if (!isPlatform && isRelevantSection && item.type === "category" && !checkIfAnyChildIsRelevantSection(item)) {
		return null;
	}

	// Hide workspace and excel links when not in those sections
	if (
		!(isPro || isExcel) &&
		(item.href?.startsWith("/workspace") || item.href?.startsWith("/excel"))
	) {
		return null;
	}

	let addedHtml = null;
	let afterHtml = null;

	switch (item.type) {
		case "category":
			return (
				<>
					{addedHtml}
					<DocSidebarItemCategory 
						item={item} 
						{...props} 
					/>
					{afterHtml}
				</>
			);
		case "html":
			return (
				<>
					{addedHtml}
					<DocSidebarItemHtml item={item} {...props} />
					{afterHtml}
				</>
			);
		case "link":
		default:
			return (
				<>
					{addedHtml}
					<DocSidebarItemLink item={item} {...props} />
					{afterHtml}
				</>
			);
	}
}

function checkIfOnlyWorkspaceItems(item) {
	if (!item.items || item.items.length === 0) {
		return false;
	}
	
	// Check if all items in this category are workspace-related
	return item.items.every((childItem) => {
		if (childItem.type === "link") {
			return childItem.href?.startsWith("/workspace");
		}
		if (childItem.type === "doc") {
			return childItem.id?.startsWith("workspace/") || 
				   childItem.docId?.startsWith("workspace/");
		}
		if (childItem.type === "category") {
			// Also check the category's items
			return checkIfOnlyWorkspaceItems(childItem);
		}
		// For autogenerated items, check dirName
		if (childItem.type === "autogenerated") {
			return childItem.dirName?.startsWith("workspace");
		}
		return false;
	});
}

function checkIfAnyChildIsRelevantSection(item) {
	if (item.items) {
		return item.items.some((childItem) => checkIfAnyChildIsRelevantSection(childItem));
	}

	if (item.type === "link") {
		return (
			item.href?.startsWith("/workspace") || 
			item.href?.startsWith("/excel") ||
			item.href?.startsWith("/getting-started")
		);
	}

	if (item.type === "category") {
		return item.items.some((childItem) => checkIfAnyChildIsRelevantSection(childItem));
	}

	return false;
}
